### PR TITLE
Use mocked api calls to test and then fix specific wallet state situations

### LINKED ISSUE #35: Deduplicate UTXOs & Remove UTXO's from Wallet After They're Spent

### LINKED ISSUE #40: Enable Sending Of Kaspa From Wallet UI

### LINKED ISSUE #47: api helpers should handle pagination
GET transasction, GET utxo, ...

### LINKED ISSUE #52: Move the cursor on receive address derivation when transaction activity detected

### LINKED ISSUE #64: Remove GET block timestamp retrieval calls
We will order by confirmations; GET block no longer needed.

### PR DESCRIPTION
**Pull request by wildmolasses**
Resolves #35
Resolves #40 
Resolves #47
Resolves #52
Resolves #64

There are 2 parts to this PR. One part is the mocked api calls and related tests. Currently we're using 3 different "state snapshots," each corresponding to a different point in a wallet's life. [here's](https://github.com/ScopeLift/kaspa-wallet/blob/ab5e7375789aea44536a8abf63aad13faf18fb95/test/jest/data/comprehensive/state1.js) an example of 1 state snapshot. We have some transactions and UTXOs. the next state snapshot changes the state to what it should look like when a transaction is sent (including new change address UTXO/tx), and finally state 3 is what happens when a tx is sent from another wallet to our receive address. Setting this up was the only way I could think of to have more confidence around utxo management, balance movement, receive/change address advancement, and pending tx management. 

The other part of this PR is fixing some things that were wrong. We have more reliable balances. sendTx works multiple times in a row (ha). When the wallet sees activity on its current receive address, it will derive a new one. All stuff that was mostly implemented, but needed some tweaking.

Finally I moved the address discovery to just one place, and I made the call to updateState more discerning so we're making the minimum number of api calls. I added a "refresh data" button to the WalletBalance. I removed the obsolete GET block calls from the transaction parsing.

### CODE REVIEW

File: src/wallet/Wallet.ts [hunk 1]
```diff
@@ -102,28 +103,29 @@ class Wallet {
...
-      return map;
-    }, {});
-    this.transactions = txParser(
-      this.transactionsStorage,
-      Object.keys(this.addressManager.all),
-      blockTimestamps
-    );
+    this.transactions = txParser(this.transactionsStorage, Object.keys(this.addressManager.all));
+    const pendingTxHashes = Object.keys(this.pending.transactions);
+    if (pendingTxHashes.length) {
```
Comment (apbendi) [inline src/wallet/Wallet.ts:117]: Extreeeeemely small nitpick here (sorry) but I tend to dislike tests like this that use 0 as falsey. Would prefer the explicit `pendingTxHashes.lenght > 0` if you don't mind.

File: src/wallet/Wallet.ts [hunk 2]
```diff
@@ -102,28 +103,29 @@ class Wallet {
...
+      pendingTxHashes.forEach((hash) => {
+        if (this.transactions.map((tx) => tx.transactionHash).includes(hash)) {
+          this.deletePendingTx(hash);
+        }
+      });
+    }
+    if (
+      this.transactionsStorage[this.addressManager.receiveAddress.current.address] !== undefined
```
Comment (apbendi) [inline src/wallet/Wallet.ts:125]: What do you think about pulling this out into a named boolean variable defined above? Solves the formatting issue and makes the code a bit more readable, because I'm not sure what this check is supposed to be telling us.

Maybe something like

```javascript
const receiveAddrHaxTx = this.transactionsStorage[this.addressManager.receiveAddress.current.address] !== undefined;

if (receiveAddrHasTx) {
    this.addressManager.receiveAddress.next();
}
```

**Comment by wildmolasses** [comment]
> If so, I'm wondering if there is any straightforward way to get a brand new tx added to the list provisionally, even before it's known about by the responding endpoint.

Yes! pursuant to #66, we just need to iterate over `wallet.pending.transactions` in the UI in order to achieve this. Once we hear about the transaction from an API response, the tx is removed from `wallet.pending.transactions`. Should feel pretty clean hopefully.

File: src/wallet/Wallet.ts (hunk 1 above)
Comment (wildmolasses) [reply src/wallet/Wallet.ts]: Love the nitpicking! Updated!

File: src/wallet/Wallet.ts (hunk 2 above)
Comment (wildmolasses) [reply src/wallet/Wallet.ts]: Thanks Ben, updated!
